/*
CREATE TABLE QUESTOES (
	CODIGO  INTEGER , 
	DATAREGISTRO  DATETIME  NOT NULL , 
	CAMPOQUESTAO  VARCHAR(8000)  DEFAULT '' NOT NULL , 
	OBSERVACAOQUESTAO  VARCHAR(8000)  DEFAULT '' NOT NULL , 
	MATERIA  VARCHAR(300)  DEFAULT '' NOT NULL , 
	CODIGOPROVA  INTEGER  DEFAULT 0 NOT NULL 
,  PRIMARY KEY ( CODIGO  )
)

CREATE TABLE ANEXOSQUESTOES (
CODIGO  INTEGER , 
CODIGOQUESTAO  INTEGER  DEFAULT 0 NOT NULL , 
DATAREGISTRO  DATETIME  DEFAULT '' NOT NULL , 
ANEXO  VARBINARY(max)  NOT NULL 
,  PRIMARY KEY ( CODIGO  )
)

CREATE TABLE RESPOSTASQUESTOES (
CODIGO  INTEGER , 
CODIGOQUESTAO  INTEGER  DEFAULT 0 NOT NULL , 
DATAREGISTRO  DATETIME  DEFAULT '' NOT NULL , 
TEXTORESPOSTA  VARCHAR(8000)  DEFAULT '' NOT NULL , 
CERTA  CHAR(1)  DEFAULT '0' NOT NULL , 
OBSERVACAORESPOSTA  VARCHAR(8000) 
,  PRIMARY KEY ( CODIGO  )
)

CREATE TABLE ANEXORESPOSTA (
CODIGO  INTEGER , 
CODIGOQUESTAO  INTEGER  DEFAULT 0 NOT NULL , 
DATAREGISTRO  DATETIME  DEFAULT '' NOT NULL , 
ANEXO  VARBINARY(max)  NOT NULL 
,  PRIMARY KEY ( CODIGO  )
)

ALTER TABLE rodrigo.QUESTOES ADD NUMEROQUESTAO VARCHAR(20)

CREATE TABLE CONFIGURACAOEMAIL (
CODIGO  INTEGER , 
EMAILREMETENTE  VARCHAR(300)  DEFAULT '' NOT NULL , 
SMTPCLIENT  VARCHAR(100) , 
PORTA  INTEGER  DEFAULT 587 NOT NULL , 
EMAILCREDENCIAL  VARCHAR(300)  DEFAULT '' NOT NULL , 
SENHACREDENCIAL  VARCHAR(200)  DEFAULT '' NOT NULL 
,  PRIMARY KEY ( CODIGO  )
)

;

CREATE TABLE EMAIL (
CODIGO  INTEGER , 
DESTINATARIO  VARCHAR(300)  DEFAULT '' NOT NULL , 
ASSUNTO  VARCHAR(300)  DEFAULT '' NOT NULL , 
TEXTO  VARCHAR(8000)  DEFAULT '' NOT NULL , 
DATAENVIO  DATETIME  NOT NULL , 
STATUS  CHAR(1)  DEFAULT '0' NOT NULL , 
OBSERVACAO  VARCHAR(1000) 
,  PRIMARY KEY ( CODIGO  )
)

;

CREATE TABLE EMAILANEXOS (
CODIGO  INTEGER , 
CODIGOEMAIL  INTEGER  DEFAULT 0 NOT NULL , 
ARQUIVO  VARBINARY  NOT NULL 
,  PRIMARY KEY ( CODIGO  )
)

;

CREATE TABLE RECUPERASENHACONCURSANDO (
CODIGO  INTEGER , 
DATAREGISTRO  DATETIME  NOT NULL , 
GUID  VARCHAR(64)  DEFAULT '' NOT NULL , 
EMAIL  VARCHAR(300)  DEFAULT '' NOT NULL 
,  PRIMARY KEY ( CODIGO  )
)
ALTER TABLE RECUPERASENHACONCURSANDO ADD RECUPERADO CHAR(1) DEFAULT '0' NOT NULL
*/


SELECT * FROM rodrigo.PROVA
SELECT * FROM rodrigo.USUARIOCONCURSANDO
SELECT * FROM rodrigo.QUESTOES
--DELETE FROM rodrigo.QUESTOES WHERE CODIGO = 11
--delete FROM rodrigo.QUESTOES
SELECT * FROM rodrigo.RESPOSTASQUESTOES WHERE CODIGOQUESTAO = 13
--DELETE FROM rodrigo.RESPOSTASQUESTOES WHERE CODIGOQUESTAO = 9
--delete FROM rodrigo.RESPOSTASQUESTOES
SELECT * FROM rodrigo.ANEXOSQUESTOES

SELECT * FROM rodrigo.ANEXORESPOSTA
--'46792755' - 12345
--'1450575459' - 123456
SELECT * FROM ACAOUSUARIO



SELECT * FROM rodrigo.CONFIGURACAOEMAIL
--'smtp.gmail.com'
UPDATE rodrigo.CONFIGURACAOEMAIL SET SMTPCLIENT = 'smtp.gmail.com'

SELECT status, * FROM rodrigo.EMAIL
SELECT * FROM rodrigo.ACAOUSUARIO
--UPDATE rodrigo.EMAIL SET STATUS = 2
--DELETE FROM rodrigo.EMAIL WHERE DESTINATARIO = ''

SELECT CODIGO FROM CODIGOS_TABLE WHERE TABELA ='EMAIL'
SELECT * FROM RECUPERASENHACONCURSANDO
